package dev.hypershot.core;

public enum CapturePhase {
    QUEUED, PREPARING_SCENE, WAITING_FOR_CHUNKS, CAPTURING_TILES, ACCUMULATING_SAMPLES,
    ENCODING, WRITING_METADATA, GENERATING_THUMBNAIL, FINALIZING, COMPLETE, PAUSED, CANCELLED, FAILED
}
